name: Sealos-Cloud

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2,14 * * *"

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hhyasdf/image-sync-action@v1.1
        with:
          auth_file: ./auth.yaml
          images_file: ./sealos-cloud.yaml
          version: latest
          proc: 20
        env:
          ALI_USERNAME: ${{ secrets.ALI_USERNAME }}
          ALI_PASSWORD: ${{ secrets.ALI_PASSWORD }}
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_PASSWORD: ${{ secrets.GHCR_PASSWORD }}